/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trafficserver;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.Timer;


/**
 *
 * @author Visakh Venugopal
 */
public class TrafficServer extends javax.swing.JFrame 
{

    //App Variables
    
    Canvas painter;
    ManagerPanel manager;
    StatisticsPanel analyst;
    ServerAdmin serverAdmin ;
    
    static public AStarImpl aStarAlgorithm ;
    private javax.swing.JButton currentMenu = null;
    private javax.swing.JPanel currentPanel = null;
    private boolean isServiceActive = false ; 
    /**
     * Creates new form TrafficServer
     */
    public TrafficServer() throws InterruptedException 
    {
        //LoginForm LF= new LoginForm();
        
        initComponents();
        
        //Menu initianlization
        painter = new Canvas();
        manager = new ManagerPanel();
        analyst = new StatisticsPanel();
        serverAdmin = new ServerAdmin();
        //aStarAlgorithm = new AStarImpl();
        //nodelistener = new NodeListener();
        
        painter.setVisible(false);
        manager.setVisible(false);
        analyst.setVisible(false);
              
        currentMenu = buttonManage;
        currentPanel = manager;
       
        this.buttonManage.setBackground(new java.awt.Color(0,204,204));       
        this.buttonServiceState.setBackground(java.awt.Color.GREEN);
        this.buttonServiceState.setText("START");
        
        this.panelBody.add(manager);
        this.panelBody.add(painter);
        this.panelBody.add(analyst);
        
        manager.setVisible(true);
        this.panelBody.updateUI();
        
        Calendar now = Calendar.getInstance();
        final DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        new Timer(1000, new ActionListener() {
        @Override
                public void actionPerformed(ActionEvent e)
                {
                    Calendar now = Calendar.getInstance();
                    labelTimeDisplay.setText(dateFormat.format(now.getTime()));
                }
            }).start();
        
        //test
        //aStarAlgorithm.aStarPath("105", "121");
    }
    
    private void menuSelected(javax.swing.JButton currentBtn,javax.swing.JPanel currentPnl)
    {
        currentMenu.setBackground(new java.awt.Color(255,204,0));
        currentMenu = currentBtn;
        currentMenu.setBackground(new java.awt.Color(0,204,204));
        
        currentPanel.setVisible(false);
        currentPanel = currentPnl;
        currentPanel.setVisible(true);
        
        this.panelBody.updateUI();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_Main = new javax.swing.JPanel();
        panelHead = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelTitleDef = new javax.swing.JLabel();
        labelTimeDisplay = new javax.swing.JLabel();
        panelNavigation = new javax.swing.JPanel();
        buttonManage = new javax.swing.JButton();
        buttonGraphView = new javax.swing.JButton();
        buttonStatitics = new javax.swing.JButton();
        panelBody = new javax.swing.JPanel();
        buttonServiceState = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setMinimumSize(new java.awt.Dimension(800, 600));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        Pnl_Main.setBackground(new java.awt.Color(51, 51, 51));

        panelHead.setBackground(new java.awt.Color(102, 102, 102));
        panelHead.setForeground(new java.awt.Color(255, 255, 255));

        labelTitle.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 48)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 153, 0));
        labelTitle.setText("ITcaS");

        labelTitleDef.setForeground(new java.awt.Color(255, 255, 255));
        labelTitleDef.setText(" Intelligent Traffic Congestion Avoidence System");

        labelTimeDisplay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTimeDisplay.setForeground(new java.awt.Color(0, 255, 204));
        labelTimeDisplay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTimeDisplay.setText("time");
        labelTimeDisplay.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        labelTimeDisplay.setAlignmentX(1.0F);

        javax.swing.GroupLayout panelHeadLayout = new javax.swing.GroupLayout(panelHead);
        panelHead.setLayout(panelHeadLayout);
        panelHeadLayout.setHorizontalGroup(
            panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeadLayout.createSequentialGroup()
                        .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelHeadLayout.createSequentialGroup()
                        .addComponent(labelTitleDef, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                        .addComponent(labelTimeDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelHeadLayout.setVerticalGroup(
            panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitleDef)
                    .addComponent(labelTimeDisplay))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelNavigation.setOpaque(false);
        panelNavigation.setLayout(new java.awt.GridLayout(3, 1));

        buttonManage.setBackground(new java.awt.Color(255, 204, 0));
        buttonManage.setText("Manage Network");
        buttonManage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonManageMouseClicked(evt);
            }
        });
        panelNavigation.add(buttonManage);

        buttonGraphView.setBackground(new java.awt.Color(255, 204, 0));
        buttonGraphView.setText("Map View");
        buttonGraphView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonGraphViewMouseClicked(evt);
            }
        });
        panelNavigation.add(buttonGraphView);

        buttonStatitics.setBackground(new java.awt.Color(255, 204, 0));
        buttonStatitics.setLabel("Statitics");
        buttonStatitics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonStatiticsMouseClicked(evt);
            }
        });
        panelNavigation.add(buttonStatitics);

        panelBody.setBackground(new java.awt.Color(153, 153, 153));
        panelBody.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));
        panelBody.setForeground(new java.awt.Color(255, 255, 255));
        panelBody.setLayout(new javax.swing.OverlayLayout(panelBody));

        buttonServiceState.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonServiceStateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Pnl_MainLayout = new javax.swing.GroupLayout(Pnl_Main);
        Pnl_Main.setLayout(Pnl_MainLayout);
        Pnl_MainLayout.setHorizontalGroup(
            Pnl_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Pnl_MainLayout.createSequentialGroup()
                        .addGroup(Pnl_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelNavigation, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(buttonServiceState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        Pnl_MainLayout.setVerticalGroup(
            Pnl_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Pnl_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_MainLayout.createSequentialGroup()
                        .addComponent(panelNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonServiceState, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        panelNavigation.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGraphViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGraphViewMouseClicked
        // TODO add your handling code here:
        if(currentMenu != buttonGraphView)
        {
            menuSelected(buttonGraphView,painter);
            //updateGraphView();
        }       
    }//GEN-LAST:event_buttonGraphViewMouseClicked

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        this.panelBody.updateUI();
    }//GEN-LAST:event_formComponentResized

    private void buttonServiceStateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonServiceStateMouseClicked
        // TODO add your handling code here:
        if(isServiceActive)
        {   this.buttonServiceState.setText("START");
            this.buttonServiceState.setBackground(java.awt.Color.GREEN);
            isServiceActive = !isServiceActive;
        }
        else
        {
            this.buttonServiceState.setText("STOP");
            this.buttonServiceState.setBackground(java.awt.Color.RED);
            serverAdmin.startCommunication();
            isServiceActive = !isServiceActive;
        }
        
    }//GEN-LAST:event_buttonServiceStateMouseClicked

    private void buttonManageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonManageMouseClicked
        // TODO add your handling code here:
        if(currentMenu != buttonManage)
        {
            menuSelected(buttonManage,manager);
        } 
    }//GEN-LAST:event_buttonManageMouseClicked

    private void buttonStatiticsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonStatiticsMouseClicked
        // TODO add your handling code here:
        if(currentMenu != buttonStatitics)
        {
            menuSelected(buttonStatitics,analyst);
        } 
    }//GEN-LAST:event_buttonStatiticsMouseClicked

    private void updateGraphView()
    {
        panelBody.removeAll();
        panelBody.add(painter);
        painter.setVisible(true);
        panelBody.updateUI();
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrafficServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrafficServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrafficServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrafficServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(() -> {
            new LoginForm().setVisible(true);
        });
        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pnl_Main;
    private javax.swing.JButton buttonGraphView;
    private javax.swing.JButton buttonManage;
    private javax.swing.JButton buttonServiceState;
    private javax.swing.JButton buttonStatitics;
    private javax.swing.JLabel labelTimeDisplay;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTitleDef;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelHead;
    private javax.swing.JPanel panelNavigation;
    // End of variables declaration//GEN-END:variables
}
